name: load-distribution-system

services:
    load-distribution-client:
        build: ./frontend
        image: load-distribution-client:${FRONTEND_IMAGE_TAG}
        container_name: ld-client-container
        restart: always
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        expose:
            - ${FRONTEND_PORT}
        depends_on:
            - load-distribution-api
        networks:
            - load-distribution-network

    load-distribution-api:
        build: ./backend
        image: load-distribution-api:${BACKEND_IMAGE_TAG}
        container_name: ld-api-container
        restart: always
        command: "uvicorn --factory src.main:create_app --port ${BACKEND_PORT} --host 0.0.0.0"
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        expose:
            - ${BACKEND_PORT}
        volumes:
            - ./logs:/logs
        networks:
            - load-distribution-network
            - postgresql-db-network
            - minio-storage-network

networks:
    load-distribution-network:
        name: load-distribution-network
        driver: bridge
    postgresql-db-network:
        external: true
    minio-storage-network:
        external: true
