version: "3.8"

services:
    frontend:
        build: ./frontend
        image: ed_frontend
        ports:
            - "3000:3000"
        expose:
            - "80"
        container_name: ed_frontend_container
        environment:
            - REACT_APP_GOOGLE_MAP_API_KEY=AIzaSyCKTTrmDykNuCPxrKd1fnCFBmszb4V3taM
            - REACT_APP_SERVICE_ID=service_x6bjhd5
            - REACT_APP_TEMPLATE_ID=template_uxvqs4p
            - REACT_APP_PUBLIC_KEY=lysH6B4MYaWkXHg2a
            - REACT_APP_SERVER_ADDRESS=backend:5000
        depends_on:
            - backend
         networks:
            - "databases_mysql_db_net"
    backend:
        build: ./backend
        image: ed_backend
        ports:
            - "5000:5000"
        expose:
            - "5000"
        container_name: ed_backend_container
        environment:
            - CLIENT_HOSTS=frontend:3000
            - SERVER_PORT=5000
            - DB_NAME=education_department
            - DB_USER=root
            - DB_USER_PASSWORD=h9_W2l@jddw_@1db
            - DB_HOST=mysql_db_net
            - DB_DIALECT=mysql
        networks:
            - "databases_mysql_db_net"

networks:
  databases_mysql_db_net:
    external: true
