version: '3'

services:
    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - SERVER_PORT=5000
            - SERVER_HOST=localhost
            - DB_NAME=education_department
            - DB_USER=root
            - DB_USER_PASSWORD=root
            - DB_HOST=localhost
            - DB_DIALECT=mysql
        depends_on:
            - db

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        ports:
            - "3306:3306"
